export default {
  dislike: require('./dislike.png'),
  like: require('./like.png'),
  nature: require('./nature.png'),
  nature2: require('./nature2.png'),
  nature3: require('./nature3.png'),
  nature4: require('./nature4.png'),
  nature5: require('./nature5.png'),
  rabbit: require('./rabbit.png'),
  squirrel: require('./squirrel.png'),
  fox: require('./fox.png'),
  cat: require('./cat.png'),
  bookmark: require('./bookmark.png'),
  comment: require('./comment.png'),
  fav: require('./fav.png'),
  arrow_back: require('./arrow_back.png'),
  avatar: require('./profileImage.png'),
  play: require('./play.png'),
  pause: require('./pause.png'),
};
