export default {
  HOME: 'Home Screen',
  GRADIENT: 'Gradient Component',
  CARD_SWIPEABLE: 'Card Swipeable Component',
  ANIMATED_LIST: 'AnimatedList Component',
  PARALLAX_HEADER: 'Parallax Header Component',
  PARALLAX_HEADER_WITH_TABS: 'With Tabs Component',
  ANIMATED_SCANNER: 'Animated Scanner',
  MEDIA_BUTTON: 'Media Button',
  ANIMATED_CHECK_MARK: 'Animated Check Mark',
  ANIMATED_WALLET: 'Animated Wallet',
  ANIMATED_SWITCH: 'Animated Switch',
  ANIMATED_NOTIFICATION: 'Animated Notification',
  ANIMATED_FLICKER_LOADER: 'Animated Flicker Loader',
  STRIKE_IMAGE: 'Strike Image',
  WIRELESS_CHARGER: 'Wireless Charger',
  HEART_RATE: 'Heart Rate',
  ANIMATED_CHARGING: 'Animated Charging',
  ANIMATED_SIGNAL: 'Animated Signal',
};
