export default {
  ANIMATION_COMPONENT: 'Animation Components',
  GRADIENT_PROGRESS_EXAMPLE: 'Gradient Progress Examples',
  CARD_SWIPEABLE_EXAMPLE: 'Card Swipeable Examples',
  ANIMATEDLIST_HORIZONTAL_EXAMPLE: 'AnimatedList Horizontal Examples',
  ANIMATEDLIST_VERTICAL_EXAMPLE: 'AnimatedList Vertical Examples',
  PARALLAX_HEADER_WITH_TABS: 'Parallax Header with Tabs',
  OPEN_PARALLAXHEADER_WITH_TABS: 'Open ParallaxHeader With Tab Example',
  PARALLAX_HEADER: 'Parallax Header',
  LETS_START: "Let's Start",
  FOLLOW: 'follow',
  FOLLOWERS: 'Followers',
  FOLLOWING: 'Following',
  SIMPLE_GRADIENT_PROGRESS_BAR: 'Simple Gradient Progress',
  CUSTOM_GRADIENT_PROGRESS: 'Custom Gradient Progress',
  GRADIENT_PROGRESS_BAR_WITH_CHILD_COMPONENT:
    'Gradient Progress with Custom Child',
  CHILD_COMPONENT: 'Child Component',
  CARD_SWIPEABLE: 'SwipeableCard Example',
  CARD_SIMPLE: 'SimpleCard Example',
  DEFAULT_MEDIA_BUTTON_WITH_PULSE: 'Simple Media Button with Pulse (Default)',
  CUSTOM_MEDIA_BUTTON_WITH_PULSE: 'Custom Media Button with Pulse',
  SIMPLE_MEDIA_BUTTON_WITH_PULSE: 'Simple Media Button without pulse',
};
