export default {
  ANIMATION_COMPONENT: 'Animation Components',
  ANIMATED_LIST: 'Animated List',
  GRADIENT_PROGRESS: 'Gradient Progress',
  CARD_SWIPEABLE: 'Card Swipeable',
  ANIMATEDLIST_HORIZONTAL: 'Horizontal AnimatedList ',
  ANIMATEDLIST_VERTICAL: 'Vertical AnimatedList',
  PARALLAX_HEADER_WITH_TABS: 'Parallax Header with Tabs',
  OPEN_PARALLAXHEADER_WITH_TABS: 'Open ParallaxHeader With Tab Example',
  HEADER_PROFILE_NAME: 'John Millar',
  LETS_START: "Let's Start",
  FOLLOW: 'follow',
  FOLLOWERS: 'Followers',
  FOLLOWING: 'Following',
  SIMPLE_GRADIENT_PROGRESS_BAR: 'Simple Gradient Progress',
  CUSTOM_GRADIENT_PROGRESS: 'Custom Gradient Progress',
  GRADIENT_PROGRESS_BAR_WITH_CHILD_COMPONENT:
    'Gradient Progress with Custom Child',
  CHILD_COMPONENT: 'Child Component',
  SWIPEABLE_CARD: 'Swipeable Card',
  CARD_SIMPLE: 'Animated Card',
  DEFAULT_MEDIA_BUTTON_WITH_PULSE: 'Simple Media Button with Pulse (Default)',
  CUSTOM_MEDIA_BUTTON_WITH_PULSE: 'Custom Media Button with Pulse',
  SIMPLE_MEDIA_BUTTON_WITH_PULSE: 'Simple Media Button without pulse',
  DEFAULT_ANIMATED_CHECK_MARK:
    '●  Animated Checkmark with fade effect and particles(default)',
  CIRCULAR_ANIMATED_CHECK_MARK:
    '●  Animated Checkmark with simple circular effect',
  SIMPLE_ANIMATED_CHECKMARK: '●  Animated Checkmark with simple effect',
  ANIMATED_SCANNER: 'Animated Scanner',
  ANIMATED_SWITCH: 'Animated Switch',
  DAY_AND_NIGHT_ANIMATED_SWITCH: 'Day and Night Animated Switch',
  SEA_THEME_ANIMATED_SWITCH: 'Sea Theme Animated Switch',
  STRIKE_IMAGE: 'Strike Image',
};
