export default {
  avatar: require('./profileImage.png'),
  reactNative: require('./react_native.png'),
  play: require('./play.png'),
  pause: require('./pause.png'),
  checkMark: require('./check.png'),
  star: require('./star.png'),
  multipleStar: require('./multipleStar.png'),
  pdf: require('./pdf.png'),
  messageBox: require('./messageBox.png'),
  river: require('./river.png'),
  middleCloud: require('./middleCloud.png'),
  upperCloud: require('./upperCloud.png'),
  lowerCloud: require('./lowerCloud.png'),
  sideCloud: require('./sideCloud.png'),
  leftCoconutTree: require('./leftCoconutTree.png'),
  rightCoconutTree: require('./rightCoconutTree.png'),
};
