export default {
  avatar: require('./profileImage.png'),
  reactNative: require('./react_native.png'),
  play: require('./play.png'),
  pause: require('./pause.png'),
  checkMark: require('./check.png'),
  star: require('./star.png'),
  multipleStar: require('./multipleStar.png'),
  pdf: require('./pdf.png'),
  messageBox: require('./messageBox.png'),
  thunder: require('./thunder.png'),
  commonWifiSignal: require('./commonWifiSignal.png'),
  leftSmallWifiSignal: require('./leftSmallWifiSignal.png'),
  rightBigWifiSignal: require('./rightBigWifiSignal.png'),
};
